// AUTH ACTION TYPES
export const SET_LOGGED_IN = 'SET_LOGGED_IN';

// Exercises
export const REQ_EXERCISES_PENDING = 'REQ_EXERCISES_PENDING';
export const REQ_EXERCISES_SUCCESS = 'REQ_EXERCISES_SUCCESS';
export const REQ_EXERCISES_ERROR = 'REQ_EXERCISES_ERROR';
